### ISSUE TITLE
Update KGL to Kotlin 1.3.70

### ISSUE THREAD

**Issue by nlbuescher** [Dominaezzz/kgl#22]
Native targets break with 1.3.70, and syntax highlighting breaks with the new plugin. There seems to have been some kind of breaking ABI change.

**Comment by Dominaezzz** [comment]
Yeah, this is going to be slightly annoying. `kotlinx-io` isn't going to upgraded anymore. At least not with the same API surface, that kgl is currently using.
The version of `kotlinx-io` being used has essentially been moved to `ktor-io`. (sigh). So all the imported package names have to be renamed. Eventually I'll just drop the dependency. #21 .
I will do the migration soon.

**Comment by nlbuescher** [comment]
Any update on this? I can go ahead and give the migration a go, if time's an issue rn

**Comment by Dominaezzz** [comment]
Oops, this fell off my radar. I just need to merge and tag.

**Comment by nlbuescher** [comment]
ah cool :+1:

**Comment by nlbuescher** [comment]
Works now with dev8
