### ISSUE TITLE
can't switch from fullscreen to windowed mode

### ISSUE THREAD

**Issue by LastExceed** [Dominaezzz/kgl#33]
to switch to windowed mode the monitor ptr must be set to null, however the `monitor` param of kgl's `window.setMonitor()` function is non-nullable, making this operation impossible

**Comment by Dominaezzz** [comment]
Ah rip, that's a bug.

If you're not using mpp you can call `glfwSetWindowMonitor` directly as a workaround.

Feel free to send a PR in the meantime. Dunno when I'll get to this myself.

**Comment by nlbuescher** [comment]
Created a fix. CI failed because of apt though. Gonna try again tomorrow.

**Comment by nlbuescher** [comment]
fixed with #34. Will be in next release
