### ISSUE TITLE
move to new maven repository due to Bintray shutdown

### ISSUE THREAD

**Issue by LastExceed** [Dominaezzz/kgl#35]
kgl is currently unavailable as a maven/gradle dependency because of this

also can you push a new release while you're at it ? still waiting for #34 to become available

**Comment by Dominaezzz** [comment]
Ah yes, BinTray is gone now, I'll be publishing kgl to GitHub packages for now.
Currently experimenting with it, once I get it working I'll publish kgl.

**Comment by Dominaezzz** [comment]
I've published `0.1.11` to GitHub packages. See README for instructions. Let me know if it works for you.

**Comment by LastExceed** [comment]
works, thanks. why is the auth necessary though ?

**Comment by Dominaezzz** [comment]
GitHub insists. https://github.community/t/download-from-github-package-registry-without-authentication/14407/121
Not really sure why but I've got my theories.

**Comment by Dominaezzz** [comment]
Glad it works!
