### ISSUE TITLE
can't resolve kgl-glfw-static library

### ISSUE THREAD

**Issue by T3sT3ro** [Dominaezzz/kgl#37]
> Could not resolve com.kgl:kgl-glfw-static:0.1.11.

Using dependencies block from your imgui project. commenting the single glfw-static dependency solves it.

```kt

val imguiVersion = "0.1.9"
val kglVersion = "0.1.11"

repositories {
    mavenCentral()

    maven ("https://maven.pkg.github.com/Dominaezzz/kotlin-imgui") {
        credentials {
            username = project.findProperty("gpr.user") as String ?: System.getenv("GITHUB_USER")
            password = project.findProperty("gpr.password") as String ?: System.getenv("GITHUB_TOKEN")
        }
    }
}

dependencies {
    implementation(kotlin("stdlib"))

    // Dear::ImGui bindings for kotlin
    implementation("com.kotlin-imgui:imgui:$imguiVersion")
    implementation("com.kotlin-imgui:imgui-glfw:$imguiVersion")
    implementation("com.kotlin-imgui:imgui-opengl:$imguiVersion")

    // For jvm binaries
    implementation("com.kotlin-imgui:cimgui-jvmlinuxx64:$imguiVersion")
    implementation("com.kotlin-imgui:cimgui-jvmmacosx64:$imguiVersion")
    implementation("com.kotlin-imgui:cimgui-jvmmingwx64:$imguiVersion")

    // Optional
    implementation("com.kgl:kgl-glfw:$kglVersion")
    implementation("com.kgl:kgl-glfw-static:$kglVersion")
    implementation("com.kgl:kgl-opengl:$kglVersion")
    implementation("com.kgl:kgl-stb:$kglVersion")
}
```

**Comment by Dominaezzz** [comment]
You're not supposed to copy that verbatim, it's only to show you the possible dependencies you might need/use. I thought the `// Optional` would've have made that clear but it looks like I need more comments there.

What are you trying to build? JVM application? Native application?

**Comment by T3sT3ro** [comment]
I just pasted a relevant part of the buildscript. I've just started an application and didn't decide on native or jvm yet.

**Comment by Dominaezzz** [comment]
You're going to have to decide that then. Some of those dependencies (like `glfw-static`) are native only.

**Comment by T3sT3ro** [comment]
Ok, my configuration was jvm so I see the problem now. It would be nice if you added some info about which libs are available for which platforms to reduce confusion.
